import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'fr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  fr: {
    // Common
    'forCompanies': 'Pour les entreprises',
    'forCandidates': 'Pour les candidats',
    'dashboard': 'Tableau de bord',
    'login': 'Connexion',

    // Navbar
    'nav.features': 'Fonctionnalités',
    'nav.success': 'Success Stories',
    'nav.pricing': 'Tarifs',
    'nav.about': 'À propos',
    'nav.companies': 'Entreprises',
    'nav.experts': 'Experts',
    'nav.start': 'Commencer',
    'nav.blog': 'Blog',

    // Hero (MercorHero)
    'hero.averagePay': 'Salaire moyen',
    'hero.dailyPayouts': 'Paiements quotidiens',
    'hero.talentEvaluated': 'Talents évalués',
    'hero.companiesHiring': 'Entreprises partenaires',
    'hero.headline': 'Prouvez vos compétences. Gagnez en visibilité. Décrochez des opportunités.',
    'hero.startWorking': 'Passer l\'évaluation',
    'hero.searchRoles': 'Découvrir les tests',

    // Latest Roles (Evaluation-based)
    'latestRoles.title': 'Évaluations techniques ouvertes',
    'latestRoles.hiredRecently': 'évalués',
    'latestRoles.apply': 'Valider mes compétences',
    'latestRoles.applyNow': 'Valider mes compétences',
    'latestRoles.subtitle': 'Score visible par les entreprises partenaires • Basé sur des cas concrets',
    'latestRoles.disclaimer': 'Évaluation 100% gratuite. Aucune garantie d\'emploi.',

    // ARES Section
    'ares.title': 'ARES Technology',
    'ares.subtitle': 'Notre intelligence artificielle de pointe qui révolutionne le recrutement tech',
    'ares.learnMore': 'En savoir plus',

    // Blog Preview
    'blog.readTime': 'min de lecture',
    'blog.viewAll': 'Voir tous les articles',

    // Testimonials
    'testimonials.meet': 'Rencontrez',

    // Footer
    'footer.forCompanies': 'Pour les entreprises',
    'footer.forCandidates': 'Pour les candidats',
    'footer.humanData': 'Human data',
    'footer.support': 'Support',
    'footer.resources': 'Ressources',
    'footer.contact': 'Nous contacter',
    'footer.privacy': 'Confidentialité',
    'footer.terms': 'Conditions',

    // Hero Stats
    'hero.badge': 'RECRUTEMENT IA NOUVELLE GÉNÉRATION',
    'hero.title': 'Les meilleurs experts tech,',
    'hero.titleHighlight': 'filtrés par l\'IA',
    'hero.subtitle': 'Notre intelligence artificielle évalue et teste automatiquement chaque profil. Recevez uniquement les candidats les plus qualifiés, classés par pertinence.',
    'hero.cta1': 'Recruter des talents',
    'hero.cta2': 'Devenir expert',
    'hero.stat1': '+500 experts actifs',
    'hero.stat2': '98% de satisfaction',
    'hero.stat3': 'Évaluation en 48h',

    // Stats Section
    'stats.badge': 'NOTRE PLATEFORME',
    'stats.title': 'Créez de meilleures solutions DevOps, Data et IA — plus rapidement',
    'stats.subtitle': 'Plus de 150 000 professionnels tech hautement qualifiés à votre disposition. Prêts à être placés rapidement et efficacement.',
    'stats.cta1': 'Recruter des talents',
    'stats.cta2': 'En savoir plus',
    'stats.value1': '150k',
    'stats.label1': 'Vivier de talents mondiaux hautement qualifiés',
    'stats.value2': '$80,000',
    'stats.label2': 'Économies par talent recruté',
    'stats.value3': '66%',
    'stats.label3': 'Recrutement plus rapide',
    'stats.value4': '33%',
    'stats.label4': 'Livraison de projet plus rapide',

    // Trusted By
    'trusted.badge': 'ILS NOUS FONT CONFIANCE',
    'trusted.title': 'Les leaders tech font confiance à notre plateforme',

    // Features
    'features.badge': 'NOTRE PLATEFORME',
    'features.title': 'Recrutement tech réinventé',
    'features.subtitle': 'Une sélectivité extrême grâce à l\'intelligence artificielle pour garantir les meilleurs talents',
    'features.1.title': 'Évaluation IA avancée',
    'features.1.desc': 'Notre IA génère des exercices techniques uniques et évalue automatiquement les compétences réelles de chaque candidat.',
    'features.2.title': 'Matching ultra-précis',
    'features.2.desc': 'Recevez uniquement les profils qui correspondent parfaitement à votre cahier des charges, classés par pertinence.',
    'features.3.title': 'Tests sécurisés',
    'features.3.desc': 'Exercices complexes et environnement contrôlé garantissent l\'authenticité des compétences évaluées.',
    'features.4.title': 'Analyse complète',
    'features.4.desc': 'Double notation : exercice technique + analyse approfondie du CV par l\'IA pour une évaluation complète.',
    'features.5.title': 'Gain de temps massif',
    'features.5.desc': 'Éliminez le tri manuel de centaines de CV. L\'IA fait le travail et vous présente les meilleurs.',
    'features.6.title': 'Qualité premium',
    'features.6.desc': 'Sélectivité maximale : seuls 15% des candidats passent nos tests IA. Vous recrutez l\'élite.',

    // How It Works
    'howItWorks.badge': 'COMMENT ÇA MARCHE',
    'howItWorks.title': 'Un processus simplifié en 3 étapes',
    'howItWorks.subtitle': 'De la définition de vos besoins à l\'embauche des meilleurs talents tech',
    'howItWorks.step1.title': 'L\'entreprise poste son besoin',
    'howItWorks.step1.desc': 'Décrivez votre poste ou soumettez un cahier des charges. Notre IA comprend vos exigences techniques et génère un test adapté.',
    'howItWorks.step2.title': 'L\'IA génère et évalue',
    'howItWorks.step2.desc': 'Chaque candidat passe un exercice technique unique et complexe. L\'IA note l\'exercice ET analyse le CV pour une double évaluation.',
    'howItWorks.step3.title': 'Les meilleurs apparaissent en tête',
    'howItWorks.step3.desc': 'Recevez une liste classée des candidats les plus qualifiés avec notes, commentaires IA détaillés et insights sur leurs compétences.',

    // Why Section
    'why.1.title': 'Recrutez partout. Livrez partout.',
    'why.1.desc': 'Trouvez les bons talents et augmentez la productivité en privilégiant les compétences et l\'expérience plutôt que la localisation.',
    'why.2.title': 'Faites avancer le travail rapidement.',
    'why.2.desc': 'Obtenez les ressources dont vous avez besoin, quand vous en avez besoin. Intégrez facilement. Réduisez les arriérés.',
    'why.3.title': 'Changez aussi rapidement que vos priorités.',
    'why.3.desc': 'Augmentez ou réduisez l\'échelle selon l\'évolution des besoins de votre entreprise.',
    'why.4.title': 'Laissez-nous le travail préparatoire.',
    'why.4.desc': 'Nous simplifions la complexité du recrutement mondial en vous assurant de ne rencontrer que des talents qualifiés.',
    'why.5.title': 'Travaillez comme vous le souhaitez.',
    'why.5.desc': 'Recrutez pour des rôles spécifiques, combler des lacunes de compétences ou faire livrer des projets à temps.',

    // Adaptive Hiring
    'adaptive.title': 'Travaillez comme vous le souhaitez',
    'adaptive.subtitle': 'Notre approche flexible vous permet de créer et gérer vos équipes selon vos besoins',
    'adaptive.1.title': 'Recrutement individuel',
    'adaptive.1.desc': 'Comblez un manque critique ou placez un résolveur de problèmes hautement qualifié.',
    'adaptive.2.title': 'Projets gérés',
    'adaptive.2.desc': 'Nous assurons une livraison dans les délais et le budget pour les projets les plus exigeants.',

    // Success Stories
    'success.badge': 'SUCCESS STORIES',
    'success.title': 'Reprenez tous vos projets en main',
    'success.1.category': 'Ingénierie Applicative',
    'success.1.title': 'Augmentation de part de marché avec services de recrutement bout à bout',
    'success.1.desc': 'Nous avons fourni des services de recrutement de bout en bout et intégré rapidement 10 ingénieurs qualifiés.',
    'success.2.category': 'Intelligence Artificielle',
    'success.2.title': 'Extension du framework ML pour la croissance des revenus',
    'success.2.desc': 'L\'équipe d\'analyse de données d\'entreprise avait besoin d\'étendre son framework d\'apprentissage automatique.',

    // CTA
    'cta.badge': 'PRÊT À COMMENCER',
    'cta.title': 'Prêt à révolutionner votre',
    'cta.titleBreak': 'recrutement tech ?',
    'cta.subtitle': 'Rejoignez les entreprises qui font confiance à l\'IA pour recruter les meilleurs talents',
    'cta.companies.title': 'Pour les entreprises',
    'cta.companies.desc': 'Recrutez des experts tech qualifiés et testés par IA.',
    'cta.companies.cta': 'Poster une offre',
    'cta.experts.title': 'Pour les experts',
    'cta.experts.desc': 'Trouvez des missions qui correspondent à vos compétences.',
    'cta.experts.cta': 'Créer mon profil',
    
    // Auth Page
    'auth.platform': 'Plateforme de recrutement tech',
    'auth.login': 'Connexion',
    'auth.signup': 'Inscription',
    'auth.createAccount': 'Créer un compte expert',
    'auth.signInToAccount': 'Connectez-vous à votre compte',
    'auth.signUpExpert': 'Créez votre compte expert pour accéder aux offres',
    'auth.signUpToStart': 'Inscrivez-vous pour commencer',
    'auth.companyNotice': 'Vous êtes une entreprise ?',
    'auth.contactUs': 'Nous contacter',
    'auth.email': 'Email',
    'auth.password': 'Mot de passe',
    'auth.fullName': 'Nom complet',
    'auth.companyName': 'Nom de l\'entreprise',
    'auth.accountType': 'Type de compte',
    'auth.company': 'Entreprise',
    'auth.expert': 'Expert',
    'auth.loggingIn': 'Connexion...',
    'auth.signIn': 'Se connecter',
    'auth.signingUp': 'Inscription...',
    'auth.createMyAccount': 'Créer mon compte',
    'auth.backToHome': '← Retour à l\'accueil',
    'auth.fillAllFields': 'Veuillez remplir tous les champs',
    'auth.passwordLength': 'Le mot de passe doit contenir au moins 6 caractères',
    'auth.companyNameRequired': 'Le nom de l\'entreprise est requis',
    'auth.loginSuccess': 'Connexion réussie !',
    'auth.accountCreated': 'Compte créé avec succès !',
    'auth.loginError': 'Erreur de connexion',
    'auth.signupError': 'Erreur lors de l\'inscription',
    'auth.passwordMin': 'Au moins 6 caractères',

    // Company Contact
    'contact.step1': 'Votre nom',
    'contact.step2': 'Email professionnel',
    'contact.step3': 'Entreprise',
    'contact.step4': 'Téléphone',
    'contact.step5': 'Raison du contact',
    'contact.step6': 'Votre message',
    'contact.next': 'Suivant',
    'contact.previous': 'Précédent',
    'contact.submit': 'Envoyer',
    'contact.sending': 'Envoi en cours...',
    'contact.success': 'Message envoyé avec succès !',
    'contact.reasons.hiring': 'Recruter des talents',
    'contact.reasons.partnership': 'Partenariat',
    'contact.reasons.demo': 'Demande de démo',
    'contact.reasons.other': 'Autre',
    
    // Auth Dialog (popup)
    'auth.createAccountTitle': 'Rejoindre le talent pool',
    'auth.createAccountDesc': 'Créez votre compte pour accéder aux évaluations techniques et intégrer notre vivier de talents qualifiés.',
    'auth.continueBrowsing': 'Continuer sans compte',
    
    // Job Details
    'job.keyResponsibilities': 'Responsabilités clés',
    'job.needToHave': 'Compétences requises',
    'job.goodToHave': 'Compétences appréciées',
    'job.continueApplication': 'Continuer la candidature',
    'job.applied': 'Candidature envoyée',
    'job.sending': 'Envoi en cours...',
    'job.hiredRecently': 'recrutés récemment',
    'job.notFound': 'Offre non trouvée',
    'job.backToExplore': 'Retour aux offres',
    'job.completeProfile': 'Veuillez compléter votre profil',
    'job.alreadyApplied': 'Vous avez déjà postulé',
    'job.applicationSent': 'Candidature envoyée !',
    'job.applicationError': 'Erreur lors de la candidature',
    'job.savedJob': 'Offre sauvegardée',
    'job.removedFromSaved': 'Retiré des favoris',
    'job.aiAnalysis': 'Analyse IA en cours...',
    'job.generatingRequirements': 'Génération du résumé et des compétences requises',
    'job.takeTest': 'Passer le test',
    'job.apply': 'Postuler',
    'job.confirmApplyTitle': 'Confirmer le passage du test',
    'job.confirmApplyDesc': 'Vous allez démarrer une évaluation technique chronométrée. Assurez-vous d\'être dans un environnement calme et d\'avoir suffisamment de temps. Cette action est irréversible.',
    'job.cancel': 'Annuler',
    'job.confirmStart': 'Démarrer le test',
    
    // Error
    'error.loadFailed': 'Échec du chargement des données',
    'error.retry': 'Réessayer',
    
    // Dashboard
    'dashboard.welcomeBack': 'Bon retour',
    'dashboard.importantTasks': 'Tâches importantes',
    'dashboard.setupPayments': 'Configurer vos paiements',
    'dashboard.setupPaymentsDesc': 'Ajoutez vos coordonnées de paiement pour commencer à être payé.',
    'dashboard.setupNow': 'Configurer maintenant',
    'dashboard.contracts': 'Contrats',
    'dashboard.offers': 'Offres',
    'dashboard.applications': 'Candidatures',
    'dashboard.noContracts': 'Aucun contrat actif',
    'dashboard.noOffers': 'Aucune offre pour le moment',
    'dashboard.noApplications': 'Aucune candidature',
    'dashboard.exploreOpportunities': 'Explorer les offres',
    'dashboard.keepApplying': 'Continuez à valider vos compétences pour accéder à plus d\'opportunités',
    'dashboard.reviewOffer': 'Examiner et accepter cette offre',
    'dashboard.accept': 'Accepter',
    'dashboard.applied': 'Postulé le',
    'dashboard.pendingTest': 'Test en attente',
    'dashboard.underReview': 'En cours d\'examen',
    'dashboard.offerReceived': 'Offre reçue',
    'dashboard.hired': 'Embauché',
    'dashboard.rejected': 'Refusé',
    'dashboard.testRequired': 'Complétez le test technique pour finaliser votre candidature',
    'dashboard.takeTest': 'Passer le test',
    'dashboard.testCompleted': 'Test complété',
    'dashboard.viewResults': 'Voir les résultats',
    'dashboard.faq': 'Questions fréquentes',
    'dashboard.howGetPaid': 'Comment suis-je payé ?',
    'dashboard.hiringProcess': 'Quel est le processus de recrutement ?',
    'dashboard.updateProfile': 'Comment mettre à jour mon profil ?',
    'dashboard.contactSupport': 'Contacter le support',
    'dashboard.notifications': 'Préférences de notification',
    'dashboard.manageNotifications': 'Gérez vos paramètres de notifications email et push.',
    'dashboard.manage': 'Gérer',
    'dashboard.needHelp': 'Besoin d\'aide ?',
    // Test
    'test.profileNotFound': 'Profil expert non trouvé. Veuillez compléter votre onboarding.',
    'test.title': 'Test Technique',
    'test.forJob': 'Test pour',
    'test.backToDashboard': 'Retour au dashboard',

    // Expert Profile Page
    'profile.title': 'Profil',
    'profile.resume': 'CV',
    'profile.availability': 'Disponibilité',
    'profile.workPreferences': 'Préférences de travail',
    'profile.notifications': 'Notifications',
    'profile.account': 'Compte',
    'profile.calendar': 'Calendrier',
    'profile.fullName': 'Nom complet',
    'profile.professionalTitle': 'Titre professionnel',
    'profile.bio': 'Biographie',
    'profile.yearsExperience': 'Années d\'expérience',
    'profile.dailyRate': 'Tarif journalier',
    'profile.cvResume': 'CV / Résumé',
    'profile.uploadCV': 'Télécharger votre CV',
    'profile.replace': 'Remplacer',
    'profile.chooseFile': 'Choisir un fichier',
    'profile.linkedin': 'LinkedIn',
    'profile.github': 'GitHub',
    'profile.portfolio': 'Portfolio',
    'profile.saveChanges': 'Sauvegarder',
    'profile.availabilityStatus': 'Statut de disponibilité',
    'profile.immediate': 'Disponible immédiatement',
    'profile.twoWeeks': 'Disponible dans 2 semaines',
    'profile.oneMonth': 'Disponible dans 1 mois',
    'profile.notAvailable': 'Non disponible actuellement',
    'profile.country': 'Pays',
    'profile.city': 'Ville',
    'profile.preferredWorkType': 'Type de travail préféré',
    'profile.remote': 'À distance',
    'profile.hybrid': 'Hybride',
    'profile.onsite': 'Sur site',
    'profile.contractTypes': 'Types de contrat',
    'profile.fulltime': 'Temps plein',
    'profile.parttime': 'Temps partiel',
    'profile.freelance': 'Freelance',
    'profile.contract': 'Contrat',
    'profile.session': 'Session',
    'profile.logout': 'Se déconnecter',
    'profile.deleteAccount': 'Supprimer le compte',
    'profile.deleteAccountDesc': 'Supprimer définitivement le compte et toutes les données de la plateforme Stef.',
    'profile.changeEmail': 'Changer d\'email',
    'profile.logoutDesc': 'Déconnectez-vous de votre session actuelle.',
    'profile.calendarTitle': 'Gérez vos disponibilités',
    'profile.calendarDesc': 'Indiquez vos périodes de disponibilité et d\'indisponibilité pour aider les recruteurs à vous contacter au bon moment.',
    'profile.notFound': 'Profil introuvable',
    'profile.notFoundDesc': 'Aucun profil expert n\'a été trouvé pour votre compte. Veuillez compléter l\'onboarding.',
    'profile.completeOnboarding': 'Compléter l\'onboarding',
    'profile.accountSection': 'Compte',
    'profile.accountSectionDesc': 'Gérez vos préférences et supprimez votre compte.',
    'profile.changeAvatar': 'Changer l\'avatar',
    'profile.avatarInfo': 'JPG, PNG ou GIF. Max 2 Mo.',
    'profile.generativePhotos': 'Photos de profil génératives',
    'profile.generativePhotosDesc': 'Laissez Stef générer une photo professionnelle à partir de votre entretien IA.',
    'profile.payoutPrefs': 'Préférences de paiement',
    'profile.payoutPrefsDesc': 'Choisissez comment vous souhaitez recevoir vos paiements.',
    'profile.paymentRequired': 'Configuration du paiement requise',
    'profile.paymentRequiredDesc': 'Complétez la configuration de votre méthode de paiement lors de l\'acceptation d\'un emploi.',
    'profile.email': 'Email',
    'profile.changeEmailBtn': 'Changer d\'email',
    'profile.deleteConfirmTitle': 'Supprimer votre compte ?',
    'profile.deleteConfirmDesc': 'Cette action est irréversible. En supprimant votre compte :',
    'profile.deleteItem1': 'Vous serez immédiatement déconnecté',
    'profile.deleteItem2': 'Votre profil ne sera plus visible sur la plateforme',
    'profile.deleteItem3': 'Vos candidatures en cours seront annulées',
    'profile.deleteItem4': 'Toutes vos données seront définitivement effacées après 60 jours',
    'profile.deleteGracePeriod': 'Pendant cette période de 60 jours, vous pouvez nous contacter pour annuler la suppression.',
    'profile.deleteDataWarning': 'Les données de votre compte seront automatiquement et définitivement effacées 60 jours après la suppression.',
    'profile.deleting': 'Suppression...',
    'profile.confirmDelete': 'Oui, supprimer mon compte',

    // Availability Calendar
    'calendar.title': 'Calendrier de disponibilités',
    'calendar.addPeriod': 'Ajouter une période',
    'calendar.available': 'Disponible',
    'calendar.unavailable': 'Indisponible',
    'calendar.vacation': 'Vacances',
    'calendar.startDate': 'Date de début',
    'calendar.endDate': 'Date de fin',
    'calendar.type': 'Type',
    'calendar.notes': 'Notes',
    'calendar.save': 'Enregistrer',
    'calendar.cancel': 'Annuler',
    'calendar.delete': 'Supprimer',
    'calendar.noPeriods': 'Aucune période de disponibilité définie',
    'calendar.addFirst': 'Ajoutez votre première période de disponibilité',

    // Messages Page
    'messages.title': 'Messages',
    'messages.noConversations': 'Aucune conversation',
    'messages.startConversation': 'Commencez une nouvelle conversation',
    'messages.typeMessage': 'Tapez votre message...',
    'messages.send': 'Envoyer',
    'messages.today': "Aujourd'hui",
    'messages.yesterday': 'Hier',
    'messages.online': 'En ligne',
    'messages.offline': 'Hors ligne',
    'messages.newMessage': 'Nouveau message',
    'messages.searchConversations': 'Rechercher des conversations',
    'messages.search': 'Rechercher...',
    'messages.typePlaceholder': 'Écrivez votre message...',
    'messages.selectConversation': 'Sélectionnez une conversation',

    // Referrals Page
    'referrals.title': 'Mes parrainages',
    'referrals.subtitle': 'Gagnez $500 pour chaque ami embauché !',
    'referrals.yourCode': 'Votre code de parrainage',
    'referrals.copyLink': 'Copier',
    'referrals.copied': 'Lien copié !',
    'referrals.invite': 'Inviter',
    'referrals.inviteFriend': 'Inviter un ami',
    'referrals.howItWorks': 'Comment ça marche',
    'referrals.step1': 'Partagez votre lien',
    'referrals.step1Desc': 'Envoyez votre lien de parrainage à vos amis',
    'referrals.step2': 'Ils s\'inscrivent',
    'referrals.step2Desc': 'Vos amis créent leur compte expert',
    'referrals.step3': 'Gagnez des bonus',
    'referrals.step3Desc': 'Recevez 500$ quand ils sont embauchés',
    'referrals.yourReferrals': 'Vos parrainages',
    'referrals.noReferrals': 'Aucun parrainage encore',
    'referrals.noReferralsDesc': 'Partagez votre lien pour commencer à gagner des récompenses.',
    'referrals.copyMyLink': 'Copier mon lien',
    'referrals.status.signedUp': 'Inscrit',
    'referrals.status.applying': 'En cours',
    'referrals.status.underReview': 'Examen',
    'referrals.status.offer': 'Offre',
    'referrals.status.hired': 'Embauchés',
    'referrals.status.all': 'Total',
    'referrals.totalEarnings': 'Gains totaux',
    'referrals.pendingBonus': 'Bonus en attente',
    'referrals.paid': 'Versé',
    'referrals.confirmed': 'Confirmé',
    'referrals.pending': 'En attente',
    'referrals.bonusPaid': 'Bonus versé',
    'referrals.payoutPending': 'Versement en cours',
    'referrals.joinedOn': 'Inscrit le',
    'referrals.hiredOn': 'Embauché le',
    'referrals.orByEmail': 'ou par email',
    'referrals.sendInvitation': 'Envoyer l\'invitation',
    'referrals.yourReferralLink': 'Votre lien de parrainage',
    'referrals.perHiredFriend': 'par ami embauché',
    'referrals.bonusInfo': 'Le bonus est versé quand votre ami complète sa première mission',
    'referrals.enterEmail': 'Veuillez entrer un email',
    'referrals.inviteSent': 'Invitation envoyée à',
    'referrals.inviteError': 'Erreur lors de l\'envoi',
    'referrals.comingSoon': 'Bientôt disponible',
    'referrals.comingSoonDesc': 'Notre programme de parrainage arrive bientôt. Gagnez des bonus en invitant vos amis talentueux !',
    'referrals.comingSoonFeatures': 'Ce qui vous attend :',
    'referrals.feature1': 'Gagnez 500€ par ami embauché',
    'referrals.feature2': 'Suivi en temps réel de vos parrainages',
    'referrals.feature3': 'Paiements rapides et transparents',
    'referrals.notifyMe': 'Me notifier au lancement',
    'referrals.notifySuccess': 'Vous serez notifié dès le lancement !',

    // Earnings Page
    'earnings.title': 'Revenus',
    'earnings.subtitle': 'Suivez vos gains et paiements',
    'earnings.totalEarnings': 'Revenus totaux',
    'earnings.pendingPayments': 'Paiements en attente',
    'earnings.thisMonth': 'Ce mois',
    'earnings.lastMonth': 'Mois dernier',
    'earnings.paymentHistory': 'Historique des paiements',
    'earnings.noPayments': 'Aucun paiement pour le moment',
    'earnings.noPaymentsDesc': 'Une fois que vous aurez terminé votre première mission et reçu un paiement, il apparaîtra ici.',
    'earnings.status.paid': 'Payé',
    'earnings.status.pending': 'En attente',
    'earnings.status.processing': 'En traitement',
    'earnings.type.work': 'Travail',
    'earnings.type.referral': 'Parrainage',
    'earnings.type.bonus': 'Bonus',
    'earnings.evolution': 'Évolution des gains',
    'earnings.realtimeUpdate': 'Les données sont mises à jour en temps réel.',
    'earnings.noPaymentMethod': 'Aucune méthode de paiement connectée',
    'earnings.connectProvider': 'Connecter un fournisseur',
    'earnings.connectPaymentMethod': 'Connecter une méthode de paiement',
    'earnings.paymentMethodConnected': 'Méthode de paiement connectée',
    'earnings.change': 'Changer',
    'earnings.paymentConnected': 'Méthode de paiement connectée !',
    'earnings.paymentError': 'Échec de la connexion du paiement',
    'earnings.bankTransfer': 'Virement bancaire',
    'earnings.bankTransferDesc': 'Recevez les paiements directement sur votre compte',
    'earnings.paypalDesc': 'Paiements rapides via PayPal',
    'earnings.wiseDesc': 'Transferts internationaux à frais réduits',
    'earnings.reportDownloaded': 'Rapport téléchargé !',
    'earnings.workPayment': 'Paiement de mission',
    'earnings.colDate': 'Date',
    'earnings.colDescription': 'Description',
    'earnings.colType': 'Type',
    'earnings.colStatus': 'Statut',
    'earnings.colAmount': 'Montant',

    // Timesheets
    'timesheets.title': 'Mes CRA',
    'timesheets.subtitle': 'Comptes rendus d\'activité',
    'timesheets.month': 'Mois',
    'timesheets.year': 'Année',
    'timesheets.daysWorked': 'Jours travaillés',
    'timesheets.status': 'Statut',
    'timesheets.actions': 'Actions',
    'timesheets.submit': 'Soumettre',
    'timesheets.resubmit': 'Resoumettre',
    'timesheets.submitted': 'Soumis',
    'timesheets.approved': 'Approuvé',
    'timesheets.rejected': 'Rejeté',
    'timesheets.draft': 'Brouillon',
    'timesheets.invoiced': 'Facturé',
    'timesheets.noTimesheets': 'Aucun CRA. Créez votre premier compte rendu d\'activité.',
    'timesheets.createNew': 'Nouveau CRA',
    'timesheets.newCRA': 'Nouveau compte rendu d\'activité',
    'timesheets.mission': 'Mission',
    'timesheets.selectMission': 'Sélectionner une mission',
    'timesheets.notes': 'Notes (optionnel)',
    'timesheets.notesPlaceholder': 'Commentaires éventuels...',
    'timesheets.cancel': 'Annuler',
    'timesheets.create': 'Créer',
    'timesheets.noActiveMission': 'Vous n\'avez pas encore de mission active. Contactez l\'équipe STEF pour être affecté à une mission.',
    'timesheets.loading': 'Chargement...',
    'timesheets.period': 'Période',
    'timesheets.client': 'Client',
    'timesheets.days': 'Jours',
    'timesheets.amount': 'Montant',
    'timesheets.summary': 'Récapitulatif',
    'timesheets.drafts': 'Brouillons',
    'timesheets.pending': 'En attente',
    'timesheets.validated': 'Validé',
    'timesheets.totalDays': 'Total jours',
    'timesheets.craCreated': 'CRA créé',
    'timesheets.craSubmitted': 'CRA soumis pour validation',
    'timesheets.daysUpdated': 'Jours mis à jour',
    'timesheets.error': 'Erreur lors du chargement',
    'timesheets.profileNotFound': 'Profil expert non trouvé',

    // Explore Page
    'explore.title': 'Explorer les opportunités',
    'explore.searchPlaceholder': 'Rechercher...',
    'explore.filters': 'Filtres',
    'explore.allJobs': 'Toutes les offres',
    'explore.remote': 'Remote',
    'explore.hybrid': 'Hybride',
    'explore.onsite': 'Sur site',
    'explore.noJobs': 'Aucune offre trouvée',
    'explore.tryDifferent': 'Essayez des filtres différents',
    'explore.aiAnalysis': 'Analyse IA de votre profil en cours...',
    'explore.hiredThisMonth': 'évalués ce mois',
    'explore.applied': 'Test passé',
    'explore.applyNow': 'Passer le test',
    'explore.bestMatch': 'Meilleure correspondance',
    'explore.popular': 'Populaire',
    'explore.recent': 'Récent',
    'explore.loadMore': 'Charger plus d\'offres',
    'explore.noResultsFor': 'Aucune offre ne correspond à',
    'explore.noJobsAvailable': 'Aucune offre disponible pour le moment',

    // Onboarding
    'onboarding.title': 'Bienvenue sur Stef',
    'onboarding.subtitle': 'Complétez votre profil en quelques étapes',
    'onboarding.step': 'Étape',
    'onboarding.of': 'sur',
    'onboarding.next': 'Suivant',
    'onboarding.previous': 'Précédent',
    'onboarding.finish': 'Terminer',
    'onboarding.skip': 'Passer',
    'onboarding.personalInfo': 'Informations personnelles',
    'onboarding.professionalInfo': 'Informations professionnelles',
    'onboarding.skills': 'Compétences',
    'onboarding.preferences': 'Préférences',
    'onboarding.cvUpload': 'Téléchargement du CV',
    'onboarding.review': 'Vérification',

    // Admin Dashboard
    'admin.title': 'Administration',
    'admin.overview': 'Vue d\'ensemble',
    'admin.experts': 'Experts',
    'admin.clients': 'Clients',
    'admin.placements': 'Placements',
    'admin.invoices': 'Factures',
    'admin.timesheets': 'Feuilles de temps',
    'admin.applications': 'Candidatures',
    'admin.referrals': 'Parrainages',
    'admin.eor': 'Partenaires EOR',
    'admin.blog': 'Blog',
    'admin.analytics': 'Analytiques',
    'admin.rlhf': 'RLHF IA',

    // Client Dashboard
    'client.title': 'Tableau de bord entreprise',
    'client.findExperts': 'Trouver des experts',
    'client.myOffers': 'Mes offres',
    'client.applications': 'Candidatures',
    'client.timesheets': 'Feuilles de temps',
    'client.createOffer': 'Créer une offre',

    // Common Actions
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.view': 'Voir',
    'common.search': 'Rechercher',
    'common.filter': 'Filtrer',
    'common.export': 'Exporter',
    'common.import': 'Importer',
    'common.download': 'Télécharger',
    'common.upload': 'Téléverser',
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.confirm': 'Confirmer',
    'common.close': 'Fermer',
    'common.back': 'Retour',
    'common.next': 'Suivant',
    'common.previous': 'Précédent',
    'common.yes': 'Oui',
    'common.no': 'Non',
    'common.all': 'Tous',
    'common.none': 'Aucun',
    'common.select': 'Sélectionner',
    'common.required': 'Requis',
    'common.optional': 'Optionnel',

    // Notifications
    'notifications.title': 'Notifications',
    'notifications.markAllRead': 'Tout marquer comme lu',
    'notifications.noNotifications': 'Aucune notification',
    'notifications.preferences': 'Préférences de notifications',
    'notifications.email': 'Notifications par email',
    'notifications.sms': 'Notifications SMS',
    'notifications.jobMatches': 'Nouvelles offres correspondantes',
    'notifications.applicationUpdates': 'Mises à jour de candidature',

    // Test History
    'testHistory.title': 'Historique des tests',
    'testHistory.subtitle': 'Retrouvez tous vos tests techniques passés',
    'testHistory.noTests': 'Aucun test passé',
    'testHistory.score': 'Score',
    'testHistory.date': 'Date',
    'testHistory.job': 'Poste',
    'testHistory.viewDetails': 'Voir les détails',
    'testHistory.testsTaken': 'Tests passés',
    'testHistory.passed': 'Réussis (≥60%)',
    'testHistory.averageScore': 'Score moyen',
    'testHistory.yourSubmissions': 'Vos soumissions',
    'testHistory.technicalTest': 'Test technique',
    'testHistory.excellent': 'Excellent',
    'testHistory.good': 'Bien',
    'testHistory.passable': 'Passable',
    'testHistory.insufficient': 'Insuffisant',
    'testHistory.anomalies': 'Anomalies',
    'testHistory.unknownDate': 'Date inconnue',
    'testHistory.testScore': 'Score Test',
    'testHistory.cvScore': 'Score CV',
    'testHistory.finalScore': 'Score Final',
    'testHistory.aiFeedback': 'Feedback IA',
    'testHistory.applyToOffers': 'Postulez à des offres pour passer des tests techniques',
    'testHistory.exploreOffers': 'Explorer les offres',

    // Expert Test
    'test.expired': 'Test Expiré',
    'test.expiredMessage': 'Vous avez quitté la page pendant plus de 5 minutes. Le test a été automatiquement invalidé.',
    'test.expiredAlert': 'Pour des raisons d\'intégrité, vous ne pouvez pas reprendre ce test. Veuillez contacter le support si vous pensez qu\'il s\'agit d\'une erreur.',
    'test.completed': 'Test Technique Complété !',
    'test.yourResults': 'Voici vos résultats détaillés',
    'test.yourScore': 'Votre Score',
    'test.verifiedProfile': 'Profil Vérifié',
    'test.globalFeedback': 'Feedback Global',
    'test.skillsAssessment': 'Évaluation des Compétences',
    'test.questionDetails': 'Détail par Question',
    'test.question': 'Question',
    'test.strengths': 'Points forts',
    'test.recommendation': 'Recommandation',
    'test.recommendHire': 'Profil recommandé',
    'test.recommendMaybe': 'À considérer',
    'test.recommendNoHire': 'Non recommandé',
    'test.feedbackQuestion': 'Cette évaluation vous a-t-elle semblé juste ? Votre feedback nous aide à améliorer notre IA.',
    'test.validateSkills': 'Validez vos compétences',
    'test.alreadyTaken': 'Vous avez déjà passé un test. Votre score:',
    'test.willEvaluate': 'Ce test va évaluer :',
    'test.estimatedDuration': 'Durée estimée : 45 minutes',
    'test.questionsCount': '5 questions techniques (théorie + code)',
    'test.verifiedBadge': 'Badge "Vérifié" si score ≥ 80%',
    'test.monitoredWarning': 'Le test est surveillé. Les changements d\'onglet et les copier-coller sont détectés.',
    'test.generating': 'Génération du test...',
    'test.generatePersonalized': 'Générer mon test personnalisé',
    'test.ready': 'Test Prêt !',
    'test.questionsAndDuration': 'questions',
    'test.minutes': 'minutes',
    'test.timerWarning': 'Une fois démarré, le chronomètre ne peut pas être arrêté. Assurez-vous d\'avoir le temps nécessaire.',
    'test.startTest': 'Commencer le test',
    'test.suspiciousBehavior': 'Comportement suspect détecté. Cela sera pris en compte dans l\'évaluation.',
    'test.theory': 'Théorie',
    'test.code': 'Code',
    'test.problemSolving': 'Résolution de problème',
    'test.points': 'points',
    'test.min': 'min',
    'test.writeCode': '// Écrivez votre code ici...',
    'test.writeAnswer': 'Écrivez votre réponse ici...',
    'test.evaluationCriteria': 'Critères d\'évaluation',
    'test.previous': 'Précédent',
    'test.next': 'Suivant',
    'test.evaluating': 'Évaluation...',
    'test.submitTest': 'Soumettre le test',
    'test.latency': 'Latence',
    'test.speed': 'Débit',
    'test.vpn': 'VPN',
    'test.detected': 'Détecté',
    'test.notDetected': 'Non',
    'test.connection': 'Connexion',
    'test.loading': 'Chargement...',
    'test.return': 'Retour',

    // Language Switcher
    'language.fr': 'Français',
    'language.en': 'English',
    'language.switch': 'Changer de langue',

    // Theme
    'themeLight': 'Clair',
    'themeDark': 'Sombre',
    'themeSystem': 'Système',

    // Push Notifications
    'notifications.enableTitle': 'Activer les notifications',
    'notifications.enableDescription': 'Recevez des alertes pour les nouvelles évaluations et mises à jour, même en arrière-plan.',
    'notifications.enable': 'Activer',
    'notifications.later': 'Plus tard',
    'notifications.settings': 'Paramètres de notification',
    'notifications.pushEnabled': 'Notifications push activées',
    'notifications.pushDisabled': 'Notifications push désactivées',

    // Bottom Nav & Header i18n
    'nav.explore': 'Explorer',
    'nav.home': 'Accueil',
    'nav.certifications': 'Certifs',
    'nav.referral': 'Parrainage',
    'header.viewActivity': 'Voir toute l\'activité',

    // Dynamic application statuses
    'status.testExpired': 'Test expiré — Archivé',
    'status.sentToCompanies': 'Transmis aux entreprises partenaires',
    'status.awaitingResponse': 'En attente de réponse des entreprises',
    'status.notAdmitted': 'Non admis',
    'status.admitted': 'Candidat admis',
    'status.expiresIn': 'Expire dans',
    'status.day': 'jour',
    'status.days': 'jours',
    'dashboard.hideArchived': 'Masquer les archivées',
    'dashboard.showArchived': 'Voir les archivées',
    'dashboard.exploreJobs': 'Explorer les missions',

    // Homepage new sections
    'home.stat.evaluated': 'Talents évalués',
    'home.stat.process': 'Délai moyen',
    'home.stat.satisfaction': 'Satisfaction',
    'home.stat.companies': 'Entreprises',
    'home.stat.interviews': 'Entretiens réalisés',
    'home.trust.secure': 'Tests sécurisés anti-triche',
    'home.trust.companies': '500+ entreprises partenaires',
    'home.trusted.title': 'ILS NOUS FONT CONFIANCE',
    'home.how.badge': 'COMMENT ÇA MARCHE',
    'home.how.title': 'Un processus simple en 3 étapes',
    'home.how.step1.title': 'Publiez votre besoin',
    'home.how.step1.desc': 'Décrivez le poste ou soumettez un cahier des charges. Notre IA comprend vos exigences techniques.',
    'home.how.step2.title': 'L\'IA évalue les candidats',
    'home.how.step2.desc': 'Tests techniques uniques générés par IA, correction automatique et analyse CV approfondie.',
    'home.how.step3.title': 'Recevez les meilleurs profils',
    'home.how.step3.desc': 'Seuls les candidats qualifiés vous sont présentés, classés par pertinence et score.',
    'home.cta.title': 'Prêt à transformer votre recrutement ?',
    'home.cta.subtitle': 'Rejoignez les entreprises et experts qui font confiance à notre plateforme.',
    'home.cta.company.title': 'Entreprises',
    'home.cta.company.desc': 'Accédez à des talents tech vérifiés et pré-évalués par IA.',
    'home.cta.company.btn': 'Recruter des talents',
    'home.cta.expert.title': 'Experts',
    'home.cta.expert.desc': 'Prouvez vos compétences et accédez à des opportunités premium.',
    'home.cta.expert.btn': 'Passer l\'évaluation',
  },
  en: {
    // Common
    'forCompanies': 'For companies',
    'forCandidates': 'For candidates',
    'dashboard': 'Dashboard',
    'login': 'Log in',

    // Navbar
    'nav.features': 'Features',
    'nav.success': 'Success Stories',
    'nav.pricing': 'Pricing',
    'nav.about': 'About',
    'nav.companies': 'Companies',
    'nav.experts': 'Experts',
    'nav.start': 'Get Started',
    'nav.blog': 'Blog',

    // Hero (MercorHero)
    'hero.averagePay': 'Average pay',
    'hero.dailyPayouts': 'Daily payouts',
    'hero.talentEvaluated': 'Talent evaluated',
    'hero.companiesHiring': 'Partner companies',
    'hero.headline': 'Find top-tier, remote, AI roles for your expertise. Available only on Stef.',
    'hero.startWorking': 'Start working',
    'hero.searchRoles': 'Search roles',

    // Latest Roles (Evaluation-based)
    'latestRoles.title': 'Open Evaluations',
    'latestRoles.hiredRecently': 'candidates evaluated',
    'latestRoles.apply': 'Take the test',
    'latestRoles.applyNow': 'Take the test',
    'latestRoles.subtitle': 'Real technical tests • Expert feedback • Priority access to opportunities',
    'latestRoles.disclaimer': 'These evaluations are not direct job offers.',

    // ARES Section
    'ares.title': 'ARES Technology',
    'ares.subtitle': 'Our cutting-edge artificial intelligence revolutionizing tech recruitment',
    'ares.learnMore': 'Learn more',

    // Blog Preview
    'blog.readTime': 'min read',
    'blog.viewAll': 'View all articles',

    // Testimonials
    'testimonials.meet': 'Meet',

    // Footer
    'footer.forCompanies': 'For companies',
    'footer.forCandidates': 'For candidates',
    'footer.humanData': 'Human data',
    'footer.support': 'Support',
    'footer.resources': 'Resources',
    'footer.contact': 'Contact us',
    'footer.privacy': 'Privacy',
    'footer.terms': 'Terms',

    // Hero Stats
    'hero.badge': 'NEXT-GENERATION AI RECRUITMENT',
    'hero.title': 'The best tech experts,',
    'hero.titleHighlight': 'filtered by AI',
    'hero.subtitle': 'Our artificial intelligence automatically evaluates and tests every profile. Receive only the most qualified candidates, ranked by relevance.',
    'hero.cta1': 'Hire Talent',
    'hero.cta2': 'Become an Expert',
    'hero.stat1': '+500 active experts',
    'hero.stat2': '98% satisfaction',
    'hero.stat3': '48h evaluation',

    // Stats Section
    'stats.badge': 'OUR PLATFORM',
    'stats.title': 'Build better DevOps, Data, and AI solutions — faster',
    'stats.subtitle': 'There are more than 150,000 highly skilled tech professionals on our roster.',
    'stats.cta1': 'Hire Talent',
    'stats.cta2': 'Learn More',
    'stats.value1': '150k',
    'stats.label1': 'Top-rated, highly skilled global talent pool',
    'stats.value2': '$80,000',
    'stats.label2': 'Cost savings per talent hired',
    'stats.value3': '66%',
    'stats.label3': 'Faster time to hire',
    'stats.value4': '33%',
    'stats.label4': 'Faster project delivery',

    // Trusted By
    'trusted.badge': 'TRUSTED BY',
    'trusted.title': 'Tech leaders trust our platform',

    // Features
    'features.badge': 'OUR PLATFORM',
    'features.title': 'Tech recruitment reinvented',
    'features.subtitle': 'Extreme selectivity through artificial intelligence to guarantee the best talents',
    'features.1.title': 'Advanced AI Evaluation',
    'features.1.desc': 'Our AI generates unique technical exercises and automatically evaluates each candidate\'s real skills.',
    'features.2.title': 'Ultra-precise Matching',
    'features.2.desc': 'Receive only profiles that perfectly match your specifications, ranked by relevance.',
    'features.3.title': 'Secure Tests',
    'features.3.desc': 'Complex exercises and controlled environment guarantee the authenticity of evaluated skills.',
    'features.4.title': 'Complete Analysis',
    'features.4.desc': 'Double scoring: technical exercise + in-depth AI CV analysis for complete evaluation.',
    'features.5.title': 'Massive Time Savings',
    'features.5.desc': 'Eliminate manual sorting of hundreds of CVs. AI does the work and presents you the best.',
    'features.6.title': 'Premium Quality',
    'features.6.desc': 'Maximum selectivity: only 15% of candidates pass our AI tests. You recruit the elite.',

    // How It Works
    'howItWorks.badge': 'HOW IT WORKS',
    'howItWorks.title': 'A simplified 3-step process',
    'howItWorks.subtitle': 'From defining your needs to hiring the best tech talents',
    'howItWorks.step1.title': 'Company posts their need',
    'howItWorks.step1.desc': 'Describe your position or submit a specification. Our AI understands your technical requirements.',
    'howItWorks.step2.title': 'AI generates and evaluates',
    'howItWorks.step2.desc': 'Each candidate takes a unique and complex technical exercise. AI grades the exercise AND analyzes the CV.',
    'howItWorks.step3.title': 'The best appear at the top',
    'howItWorks.step3.desc': 'Receive a ranked list of the most qualified candidates with grades and detailed AI comments.',

    // Why Section
    'why.1.title': 'Hire anywhere. Deliver everywhere.',
    'why.1.desc': 'Find the right talent and increase productivity when you prioritize skill and experience over location.',
    'why.2.title': 'Make work happen fast.',
    'why.2.desc': 'Get the resources you need, when you need them. Onboard easily. Reduce backlog.',
    'why.3.title': 'Change as quickly as your priorities do.',
    'why.3.desc': 'Scale up or down as your business needs change. Add or reduce workforce on demand.',
    'why.4.title': 'Leave the groundwork to us.',
    'why.4.desc': 'We simplify the complexity of global hiring by ensuring you meet only qualified talent.',
    'why.5.title': 'Work the way that works for you.',
    'why.5.desc': 'Hire for specific roles, to fill skill gaps, or get projects delivered on time.',

    // Adaptive Hiring
    'adaptive.title': 'Work the way that works for you',
    'adaptive.subtitle': 'Our flexible approach lets you create and manage teams in any configuration',
    'adaptive.1.title': 'Hire Individuals',
    'adaptive.1.desc': 'Fill a critical gap or place a highly skilled problem solver.',
    'adaptive.2.title': 'Create Managed Projects',
    'adaptive.2.desc': 'We ensure on time, on budget delivery for the most demanding projects.',

    // Success Stories
    'success.badge': 'SUCCESS STORIES',
    'success.title': 'Get all of your initiatives back on the table',
    'success.1.category': 'Application Engineering',
    'success.1.title': 'Growing Market Share With End-to-End Hiring Services',
    'success.1.desc': 'We provided end-to-end hiring services and quickly integrated 10 skilled engineers.',
    'success.2.category': 'Artificial Intelligence',
    'success.2.title': 'Expanding Machine Learning Framework for Revenue Growth',
    'success.2.desc': 'Enterprise Data and Analytics team needed to expand its machine learning framework.',

    // CTA
    'cta.badge': 'READY TO START',
    'cta.title': 'Ready to revolutionize your',
    'cta.titleBreak': 'tech recruitment?',
    'cta.subtitle': 'Join companies that trust AI to recruit the best talents',
    'cta.companies.title': 'For Companies',
    'cta.companies.desc': 'Recruit qualified and AI-tested tech experts.',
    'cta.companies.cta': 'Post a Job',
    'cta.experts.title': 'For Experts',
    'cta.experts.desc': 'Find missions that match your skills.',
    'cta.experts.cta': 'Create My Profile',
    
    // Auth Page
    'auth.platform': 'Tech recruitment platform',
    'auth.login': 'Login',
    'auth.signup': 'Sign Up',
    'auth.createAccount': 'Create expert account',
    'auth.signInToAccount': 'Sign in to your account',
    'auth.signUpExpert': 'Create your expert account to access job offers',
    'auth.signUpToStart': 'Sign up to get started',
    'auth.companyNotice': 'Are you a company?',
    'auth.contactUs': 'Contact us',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.fullName': 'Full name',
    'auth.companyName': 'Company name',
    'auth.accountType': 'Account type',
    'auth.company': 'Company',
    'auth.expert': 'Expert',
    'auth.loggingIn': 'Logging in...',
    'auth.signIn': 'Sign In',
    'auth.signingUp': 'Signing up...',
    'auth.createMyAccount': 'Create account',
    'auth.backToHome': '← Back to home',
    'auth.fillAllFields': 'Please fill all fields',
    'auth.passwordLength': 'Password must be at least 6 characters',
    'auth.companyNameRequired': 'Company name is required',
    'auth.loginSuccess': 'Login successful!',
    'auth.accountCreated': 'Account created successfully!',
    'auth.loginError': 'Login error',
    'auth.signupError': 'Signup error',
    'auth.passwordMin': 'At least 6 characters',

    // Company Contact
    'contact.step1': 'Your name',
    'contact.step2': 'Professional email',
    'contact.step3': 'Company',
    'contact.step4': 'Phone',
    'contact.step5': 'Reason for contact',
    'contact.step6': 'Your message',
    'contact.next': 'Next',
    'contact.previous': 'Previous',
    'contact.submit': 'Submit',
    'contact.sending': 'Sending...',
    'contact.success': 'Message sent successfully!',
    'contact.reasons.hiring': 'Hire talent',
    'contact.reasons.partnership': 'Partnership',
    'contact.reasons.demo': 'Request demo',
    'contact.reasons.other': 'Other',
    
    // Auth Dialog (popup)
    'auth.createAccountTitle': 'Join the talent pool',
    'auth.createAccountDesc': 'Create your account to access technical evaluations and join our vetted talent pool.',
    'auth.continueBrowsing': 'Continue without account',
    
    // Job Details
    'job.keyResponsibilities': 'Key Responsibilities',
    'job.needToHave': 'Need to Have',
    'job.goodToHave': 'Good to Have',
    'job.continueApplication': 'Continue Application',
    'job.applied': 'Application Sent',
    'job.sending': 'Sending...',
    'job.hiredRecently': 'hired recently',
    'job.notFound': 'Job not found',
    'job.backToExplore': 'Back to jobs',
    'job.completeProfile': 'Please complete your profile first',
    'job.alreadyApplied': 'You have already applied',
    'job.applicationSent': 'Application submitted!',
    'job.applicationError': 'Failed to apply',
    'job.savedJob': 'Job saved',
    'job.removedFromSaved': 'Removed from saved',
    'job.aiAnalysis': 'AI analysis in progress...',
    'job.generatingRequirements': 'Generating summary and required skills',
    'job.takeTest': 'Take the test',
    'job.apply': 'Apply',
    'job.confirmApplyTitle': 'Confirm test start',
    'job.confirmApplyDesc': 'You are about to start a timed technical assessment. Make sure you are in a quiet environment with enough time available. This action cannot be undone.',
    'job.cancel': 'Cancel',
    'job.confirmStart': 'Start the test',
    
    // Error
    'error.loadFailed': 'Failed to load data',
    'error.retry': 'Retry',
    
    // Dashboard
    'dashboard.welcomeBack': 'Welcome back',
    'dashboard.importantTasks': 'Important Tasks',
    'dashboard.setupPayments': 'Setup Your Payments',
    'dashboard.setupPaymentsDesc': 'Add your payment details to start getting paid.',
    'dashboard.setupNow': 'Setup Now',
    'dashboard.contracts': 'Contracts',
    'dashboard.offers': 'Offers',
    'dashboard.applications': 'Applications',
    'dashboard.noContracts': 'No active contracts',
    'dashboard.noOffers': 'No offers yet',
    'dashboard.noApplications': 'No applications yet',
    'dashboard.exploreOpportunities': 'Explore opportunities',
    'dashboard.keepApplying': 'Keep applying to get offers from companies',
    'dashboard.reviewOffer': 'Review and accept this offer',
    'dashboard.accept': 'Accept',
    'dashboard.applied': 'Applied',
    'dashboard.pendingTest': 'Test pending',
    'dashboard.underReview': 'Under review',
    'dashboard.offerReceived': 'Offer received',
    'dashboard.hired': 'Hired',
    'dashboard.rejected': 'Rejected',
    'dashboard.testRequired': 'Complete the technical test to finalize your application',
    'dashboard.takeTest': 'Take Test',
    'dashboard.testCompleted': 'Test completed',
    'dashboard.viewResults': 'View results',
    'dashboard.faq': 'Frequently Asked Questions',
    'dashboard.howGetPaid': 'How do I get paid?',
    'dashboard.hiringProcess': 'What is the hiring process?',
    'dashboard.updateProfile': 'How do I update my profile?',
    'dashboard.contactSupport': 'Contact support',
    'dashboard.notifications': 'Notification Preferences',
    'dashboard.manageNotifications': 'Manage your email and push notification settings.',
    'dashboard.manage': 'Manage',
    'dashboard.needHelp': 'Need help?',
    // Test
    'test.profileNotFound': 'Expert profile not found. Please complete your onboarding.',
    'test.title': 'Technical Test',
    'test.forJob': 'Test for',
    'test.backToDashboard': 'Back to dashboard',

    // Expert Profile Page
    'profile.title': 'Profile',
    'profile.resume': 'Resume',
    'profile.availability': 'Availability',
    'profile.workPreferences': 'Work Preferences',
    'profile.notifications': 'Notifications',
    'profile.account': 'Account',
    'profile.calendar': 'Calendar',
    'profile.fullName': 'Full Name',
    'profile.professionalTitle': 'Professional Title',
    'profile.bio': 'Bio',
    'profile.yearsExperience': 'Years of Experience',
    'profile.dailyRate': 'Daily Rate',
    'profile.cvResume': 'CV / Resume',
    'profile.uploadCV': 'Upload your CV',
    'profile.replace': 'Replace',
    'profile.chooseFile': 'Choose file',
    'profile.linkedin': 'LinkedIn',
    'profile.github': 'GitHub',
    'profile.portfolio': 'Portfolio',
    'profile.saveChanges': 'Save Changes',
    'profile.availabilityStatus': 'Availability Status',
    'profile.immediate': 'Immediately available',
    'profile.twoWeeks': 'Available in 2 weeks',
    'profile.oneMonth': 'Available in 1 month',
    'profile.notAvailable': 'Not currently available',
    'profile.country': 'Country',
    'profile.city': 'City',
    'profile.preferredWorkType': 'Preferred Work Type',
    'profile.remote': 'Remote',
    'profile.hybrid': 'Hybrid',
    'profile.onsite': 'On-site',
    'profile.contractTypes': 'Contract Types',
    'profile.fulltime': 'Full-time',
    'profile.parttime': 'Part-time',
    'profile.freelance': 'Freelance',
    'profile.contract': 'Contract',
    'profile.session': 'Session',
    'profile.logout': 'Log out',
    'profile.deleteAccount': 'Delete account',
    'profile.deleteAccountDesc': 'Permanently delete the account and all data from the Stef platform.',
    'profile.changeEmail': 'Change email',
    'profile.logoutDesc': 'Log out from your current session.',
    'profile.calendarTitle': 'Manage your availability',
    'profile.calendarDesc': 'Indicate your availability periods to help recruiters contact you at the right time.',
    'profile.notFound': 'Profile not found',
    'profile.notFoundDesc': 'No expert profile was found for your account. Please complete onboarding.',
    'profile.completeOnboarding': 'Complete onboarding',
    'profile.accountSection': 'Account',
    'profile.accountSectionDesc': 'Manage your preferences and delete your account.',
    'profile.changeAvatar': 'Change avatar',
    'profile.avatarInfo': 'JPG, PNG, or GIF. Max 2 MB.',
    'profile.generativePhotos': 'Generative profile pictures',
    'profile.generativePhotosDesc': 'Let Stef generate a professional photo from your AI interview.',
    'profile.payoutPrefs': 'Payout preferences',
    'profile.payoutPrefsDesc': 'Choose how you want to receive your payouts.',
    'profile.paymentRequired': 'Payment method setup required',
    'profile.paymentRequiredDesc': 'Complete your payment method setup during job acceptance to enable payouts.',
    'profile.email': 'Email',
    'profile.changeEmailBtn': 'Change email',
    'profile.deleteConfirmTitle': 'Delete your account?',
    'profile.deleteConfirmDesc': 'This action is irreversible. By deleting your account:',
    'profile.deleteItem1': 'You will be immediately logged out',
    'profile.deleteItem2': 'Your profile will no longer be visible on the platform',
    'profile.deleteItem3': 'Your active applications will be cancelled',
    'profile.deleteItem4': 'All your data will be permanently deleted after 60 days',
    'profile.deleteGracePeriod': 'During this 60-day period, you can contact us to cancel the deletion.',
    'profile.deleteDataWarning': 'Your account data will be automatically and permanently deleted 60 days after deletion.',
    'profile.deleting': 'Deleting...',
    'profile.confirmDelete': 'Yes, delete my account',

    // Availability Calendar
    'calendar.title': 'Availability Calendar',
    'calendar.addPeriod': 'Add period',
    'calendar.available': 'Available',
    'calendar.unavailable': 'Unavailable',
    'calendar.vacation': 'Vacation',
    'calendar.startDate': 'Start date',
    'calendar.endDate': 'End date',
    'calendar.type': 'Type',
    'calendar.notes': 'Notes',
    'calendar.save': 'Save',
    'calendar.cancel': 'Cancel',
    'calendar.delete': 'Delete',
    'calendar.noPeriods': 'No availability periods defined',
    'calendar.addFirst': 'Add your first availability period',

    // Messages Page
    'messages.title': 'Messages',
    'messages.noConversations': 'No conversations',
    'messages.startConversation': 'Start a new conversation',
    'messages.typeMessage': 'Type your message...',
    'messages.send': 'Send',
    'messages.today': 'Today',
    'messages.yesterday': 'Yesterday',
    'messages.online': 'Online',
    'messages.offline': 'Offline',
    'messages.newMessage': 'New message',
    'messages.searchConversations': 'Search conversations',

    // Referrals Page
    'referrals.title': 'My referrals',
    'referrals.subtitle': 'Earn $500 for each hired friend!',
    'referrals.yourCode': 'Your referral code',
    'referrals.copyLink': 'Copy',
    'referrals.copied': 'Link copied!',
    'referrals.invite': 'Invite',
    'referrals.inviteFriend': 'Invite a friend',
    'referrals.howItWorks': 'How it works',
    'referrals.step1': 'Share your link',
    'referrals.step1Desc': 'Send your referral link to your friends',
    'referrals.step2': 'They sign up',
    'referrals.step2Desc': 'Your friends create their expert account',
    'referrals.step3': 'Earn bonuses',
    'referrals.step3Desc': 'Get $500 when they get hired',
    'referrals.yourReferrals': 'Your referrals',
    'referrals.noReferrals': 'No referrals yet',
    'referrals.noReferralsDesc': 'Share your link to start earning rewards.',
    'referrals.copyMyLink': 'Copy my link',
    'referrals.status.signedUp': 'Signed Up',
    'referrals.status.applying': 'Applying',
    'referrals.status.underReview': 'Review',
    'referrals.status.offer': 'Offer',
    'referrals.status.hired': 'Hired',
    'referrals.status.all': 'All',
    'referrals.totalEarnings': 'Total earnings',
    'referrals.pendingBonus': 'Pending bonus',
    'referrals.paid': 'Paid',
    'referrals.confirmed': 'Confirmed',
    'referrals.pending': 'Pending',
    'referrals.bonusPaid': 'Bonus Paid',
    'referrals.payoutPending': 'Payout pending',
    'referrals.joinedOn': 'Joined',
    'referrals.hiredOn': 'Hired on',
    'referrals.orByEmail': 'or by email',
    'referrals.sendInvitation': 'Send Invite',
    'referrals.yourReferralLink': 'Your referral link',
    'referrals.perHiredFriend': 'per hired friend',
    'referrals.bonusInfo': 'Bonus is paid when your friend completes their first mission',
    'referrals.enterEmail': 'Please enter an email',
    'referrals.inviteSent': 'Invitation sent to',
    'referrals.inviteError': 'Failed to send invitation',
    'referrals.comingSoon': 'Coming Soon',
    'referrals.comingSoonDesc': 'Our referral program is coming soon. Earn bonuses by inviting your talented friends!',
    'referrals.comingSoonFeatures': 'What to expect:',
    'referrals.feature1': 'Earn $500 per hired friend',
    'referrals.feature2': 'Real-time referral tracking',
    'referrals.feature3': 'Fast and transparent payouts',
    'referrals.notifyMe': 'Notify me at launch',
    'referrals.notifySuccess': 'You will be notified at launch!',

    // Earnings Page
    'earnings.title': 'Earnings',
    'earnings.subtitle': 'Track your earnings and payments',
    'earnings.totalEarnings': 'Total earnings',
    'earnings.pendingPayments': 'Pending payments',
    'earnings.thisMonth': 'This month',
    'earnings.lastMonth': 'Last month',
    'earnings.paymentHistory': 'Payment history',
    'earnings.noPayments': 'No payments yet',
    'earnings.noPaymentsDesc': 'Once you complete your first mission and receive a payout, it will appear here.',
    'earnings.status.paid': 'Paid',
    'earnings.status.pending': 'Pending',
    'earnings.status.processing': 'Processing',
    'earnings.type.work': 'Work',
    'earnings.type.referral': 'Referral',
    'earnings.type.bonus': 'Bonus',
    'earnings.evolution': 'Earnings Evolution',
    'earnings.realtimeUpdate': 'Data is updated in real time.',
    'earnings.noPaymentMethod': 'No payment method connected',
    'earnings.connectProvider': 'Connect provider',
    'earnings.connectPaymentMethod': 'Connect Payment Method',
    'earnings.paymentMethodConnected': 'Payment method connected',
    'earnings.change': 'Change',
    'earnings.paymentConnected': 'Payment method connected!',
    'earnings.paymentError': 'Failed to connect payment method',
    'earnings.bankTransfer': 'Bank Transfer',
    'earnings.bankTransferDesc': 'Receive payments directly to your bank',
    'earnings.paypalDesc': 'Fast payments via PayPal',
    'earnings.wiseDesc': 'International transfers with low fees',
    'earnings.reportDownloaded': 'Report downloaded!',
    'earnings.workPayment': 'Work payment',
    'earnings.colDate': 'Date',
    'earnings.colDescription': 'Description',
    'earnings.colType': 'Type',
    'earnings.colStatus': 'Status',
    'earnings.colAmount': 'Amount',

    // Timesheets
    'timesheets.title': 'My Timesheets',
    'timesheets.subtitle': 'Activity reports',
    'timesheets.month': 'Month',
    'timesheets.year': 'Year',
    'timesheets.daysWorked': 'Days worked',
    'timesheets.status': 'Status',
    'timesheets.actions': 'Actions',
    'timesheets.submit': 'Submit',
    'timesheets.resubmit': 'Resubmit',
    'timesheets.submitted': 'Submitted',
    'timesheets.approved': 'Approved',
    'timesheets.rejected': 'Rejected',
    'timesheets.draft': 'Draft',
    'timesheets.invoiced': 'Invoiced',
    'timesheets.noTimesheets': 'No timesheets. Create your first activity report.',
    'timesheets.createNew': 'New Timesheet',
    'timesheets.newCRA': 'New activity report',
    'timesheets.mission': 'Mission',
    'timesheets.selectMission': 'Select a mission',
    'timesheets.notes': 'Notes (optional)',
    'timesheets.notesPlaceholder': 'Any comments...',
    'timesheets.cancel': 'Cancel',
    'timesheets.create': 'Create',
    'timesheets.noActiveMission': 'You don\'t have an active mission yet. Contact the STEF team to be assigned to a mission.',
    'timesheets.loading': 'Loading...',
    'timesheets.period': 'Period',
    'timesheets.client': 'Client',
    'timesheets.days': 'Days',
    'timesheets.amount': 'Amount',
    'timesheets.summary': 'Summary',
    'timesheets.drafts': 'Drafts',
    'timesheets.pending': 'Pending',
    'timesheets.validated': 'Validated',
    'timesheets.totalDays': 'Total days',
    'timesheets.craCreated': 'Timesheet created',
    'timesheets.craSubmitted': 'Timesheet submitted for validation',
    'timesheets.daysUpdated': 'Days updated',
    'timesheets.error': 'Error loading data',
    'timesheets.profileNotFound': 'Expert profile not found',

    // Explore Page
    'explore.title': 'Explore opportunities',
    'explore.searchPlaceholder': 'Type to search...',
    'explore.filters': 'Filters',
    'explore.allJobs': 'All jobs',
    'explore.remote': 'Remote',
    'explore.hybrid': 'Hybrid',
    'explore.onsite': 'On-site',
    'explore.noJobs': 'No jobs found',
    'explore.tryDifferent': 'Try different filters',
    'explore.aiAnalysis': 'AI analysis of your profile in progress...',
    'explore.hiredThisMonth': 'evaluated this month',
    'explore.applied': 'Test completed',
    'explore.applyNow': 'Take the test',
    'explore.bestMatch': 'Best match',
    'explore.popular': 'Popular',
    'explore.recent': 'Recent',
    'explore.saved': 'Saved',
    'explore.loadMore': 'Load more jobs',
    'explore.noResultsFor': 'No jobs match',
    'explore.noJobsAvailable': 'No jobs available at the moment',

    // Messages Page (additional keys)
    'messages.search': 'Search...',
    'messages.typePlaceholder': 'Type your message...',
    'messages.selectConversation': 'Select a conversation',

    // Onboarding
    'onboarding.title': 'Welcome to Stef',
    'onboarding.subtitle': 'Complete your profile in a few steps',
    'onboarding.step': 'Step',
    'onboarding.of': 'of',
    'onboarding.next': 'Next',
    'onboarding.previous': 'Previous',
    'onboarding.finish': 'Finish',
    'onboarding.skip': 'Skip',
    'onboarding.personalInfo': 'Personal Information',
    'onboarding.professionalInfo': 'Professional Information',
    'onboarding.skills': 'Skills',
    'onboarding.preferences': 'Preferences',
    'onboarding.cvUpload': 'CV Upload',
    'onboarding.review': 'Review',

    // Admin Dashboard
    'admin.title': 'Administration',
    'admin.overview': 'Overview',
    'admin.experts': 'Experts',
    'admin.clients': 'Clients',
    'admin.placements': 'Placements',
    'admin.invoices': 'Invoices',
    'admin.timesheets': 'Timesheets',
    'admin.applications': 'Applications',
    'admin.referrals': 'Referrals',
    'admin.eor': 'EOR Partners',
    'admin.blog': 'Blog',
    'admin.analytics': 'Analytics',
    'admin.rlhf': 'AI RLHF',

    // Client Dashboard
    'client.title': 'Company Dashboard',
    'client.findExperts': 'Find Experts',
    'client.myOffers': 'My Job Offers',
    'client.applications': 'Applications',
    'client.timesheets': 'Timesheets',
    'client.createOffer': 'Create Job Offer',

    // Common Actions
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.download': 'Download',
    'common.upload': 'Upload',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.confirm': 'Confirm',
    'common.close': 'Close',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.all': 'All',
    'common.none': 'None',
    'common.select': 'Select',
    'common.required': 'Required',
    'common.optional': 'Optional',

    // Notifications
    'notifications.title': 'Notifications',
    'notifications.markAllRead': 'Mark all as read',
    'notifications.noNotifications': 'No notifications',
    'notifications.preferences': 'Notification preferences',
    'notifications.email': 'Email notifications',
    'notifications.sms': 'SMS notifications',
    'notifications.jobMatches': 'New matching jobs',
    'notifications.applicationUpdates': 'Application updates',

    // Test History
    'testHistory.title': 'Test History',
    'testHistory.subtitle': 'View all your past technical tests',
    'testHistory.noTests': 'No tests taken',
    'testHistory.score': 'Score',
    'testHistory.date': 'Date',
    'testHistory.job': 'Position',
    'testHistory.viewDetails': 'View details',
    'testHistory.testsTaken': 'Tests taken',
    'testHistory.passed': 'Passed (≥60%)',
    'testHistory.averageScore': 'Average score',
    'testHistory.yourSubmissions': 'Your submissions',
    'testHistory.technicalTest': 'Technical test',
    'testHistory.excellent': 'Excellent',
    'testHistory.good': 'Good',
    'testHistory.passable': 'Passable',
    'testHistory.insufficient': 'Insufficient',
    'testHistory.anomalies': 'Anomalies',
    'testHistory.unknownDate': 'Unknown date',
    'testHistory.testScore': 'Test Score',
    'testHistory.cvScore': 'CV Score',
    'testHistory.finalScore': 'Final Score',
    'testHistory.aiFeedback': 'AI Feedback',
    'testHistory.applyToOffers': 'Apply to job offers to take technical tests',
    'testHistory.exploreOffers': 'Explore offers',

    // Expert Test
    'test.expired': 'Test Expired',
    'test.expiredMessage': 'You left the page for more than 5 minutes. The test has been automatically invalidated.',
    'test.expiredAlert': 'For integrity reasons, you cannot resume this test. Please contact support if you believe this is an error.',
    'test.completed': 'Technical Test Completed!',
    'test.yourResults': 'Here are your detailed results',
    'test.yourScore': 'Your Score',
    'test.verifiedProfile': 'Verified Profile',
    'test.globalFeedback': 'Global Feedback',
    'test.skillsAssessment': 'Skills Assessment',
    'test.questionDetails': 'Question Details',
    'test.question': 'Question',
    'test.strengths': 'Strengths',
    'test.recommendation': 'Recommendation',
    'test.recommendHire': 'Recommended profile',
    'test.recommendMaybe': 'To consider',
    'test.recommendNoHire': 'Not recommended',
    'test.feedbackQuestion': 'Did this evaluation seem fair to you? Your feedback helps us improve our AI.',
    'test.validateSkills': 'Validate your skills',
    'test.alreadyTaken': 'You have already taken a test. Your score:',
    'test.willEvaluate': 'This test will evaluate:',
    'test.estimatedDuration': 'Estimated duration: 45 minutes',
    'test.questionsCount': '5 technical questions (theory + code)',
    'test.verifiedBadge': '"Verified" badge if score ≥ 80%',
    'test.monitoredWarning': 'The test is monitored. Tab switches and copy-paste are detected.',
    'test.generating': 'Generating test...',
    'test.generatePersonalized': 'Generate my personalized test',
    'test.ready': 'Test Ready!',
    'test.questionsAndDuration': 'questions',
    'test.minutes': 'minutes',
    'test.timerWarning': 'Once started, the timer cannot be stopped. Make sure you have the time needed.',
    'test.startTest': 'Start the test',
    'test.suspiciousBehavior': 'Suspicious behavior detected. This will be taken into account in the evaluation.',
    'test.theory': 'Theory',
    'test.code': 'Code',
    'test.problemSolving': 'Problem solving',
    'test.points': 'points',
    'test.min': 'min',
    'test.writeCode': '// Write your code here...',
    'test.writeAnswer': 'Write your answer here...',
    'test.evaluationCriteria': 'Evaluation criteria',
    'test.previous': 'Previous',
    'test.next': 'Next',
    'test.evaluating': 'Evaluating...',
    'test.submitTest': 'Submit test',
    'test.latency': 'Latency',
    'test.speed': 'Speed',
    'test.vpn': 'VPN',
    'test.detected': 'Detected',
    'test.notDetected': 'No',
    'test.connection': 'Connection',
    'test.loading': 'Loading...',
    'test.return': 'Return',

    // Language Switcher
    'language.fr': 'Français',
    'language.en': 'English',
    'language.switch': 'Switch language',

    // Theme
    'themeLight': 'Light',
    'themeDark': 'Dark',
    'themeSystem': 'System',

    // Push Notifications
    'notifications.enableTitle': 'Enable notifications',
    'notifications.enableDescription': 'Get alerts for new evaluations and updates, even in the background.',
    'notifications.enable': 'Enable',
    'notifications.later': 'Later',
    'notifications.settings': 'Notification settings',
    'notifications.pushEnabled': 'Push notifications enabled',
    'notifications.pushDisabled': 'Push notifications disabled',

    // Bottom Nav & Header i18n
    'nav.explore': 'Explore',
    'nav.home': 'Home',
    'nav.certifications': 'Certs',
    'nav.referral': 'Referrals',
    'header.viewActivity': 'View all activity',

    // Dynamic application statuses
    'status.testExpired': 'Test expired — Archived',
    'status.sentToCompanies': 'Sent to partner companies',
    'status.awaitingResponse': 'Awaiting company response',
    'status.notAdmitted': 'Not admitted',
    'status.admitted': 'Candidate admitted',
    'status.expiresIn': 'Expires in',
    'status.day': 'day',
    'status.days': 'days',
    'dashboard.hideArchived': 'Hide archived',
    'dashboard.showArchived': 'Show archived',
    'dashboard.exploreJobs': 'Explore missions',

    // Homepage new sections
    'home.stat.evaluated': 'Talent evaluated',
    'home.stat.process': 'Average time',
    'home.stat.satisfaction': 'Satisfaction',
    'home.stat.companies': 'Companies',
    'home.stat.interviews': 'Interviews completed',
    'home.trust.secure': 'Anti-cheat secure tests',
    'home.trust.companies': '500+ partner companies',
    'home.trusted.title': 'TRUSTED BY LEADING COMPANIES',
    'home.how.badge': 'HOW IT WORKS',
    'home.how.title': 'A simple 3-step process',
    'home.how.step1.title': 'Post your need',
    'home.how.step1.desc': 'Describe the role or submit a spec. Our AI understands your technical requirements.',
    'home.how.step2.title': 'AI evaluates candidates',
    'home.how.step2.desc': 'Unique AI-generated technical tests, automated grading and in-depth CV analysis.',
    'home.how.step3.title': 'Get the best profiles',
    'home.how.step3.desc': 'Only qualified candidates are presented to you, ranked by relevance and score.',
    'home.cta.title': 'Ready to transform your hiring?',
    'home.cta.subtitle': 'Join the companies and experts who trust our platform.',
    'home.cta.company.title': 'Companies',
    'home.cta.company.desc': 'Access AI-verified and pre-evaluated tech talent.',
    'home.cta.company.btn': 'Hire talent',
    'home.cta.expert.title': 'Experts',
    'home.cta.expert.desc': 'Prove your skills and access premium opportunities.',
    'home.cta.expert.btn': 'Take the evaluation',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const stored = localStorage.getItem('language');
    return (stored as Language) || 'fr';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['fr']] || key;
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
